apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app 
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-deployments
        image: dachanh/go-deployments:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort:  3000